### PR TITLE
Create 24-104-x0r-jthermit.asm

### PR DESCRIPTION
**Pull request by viiri**
Honest, but fast and small solution.

### CODE REVIEW

**Comment by nanashi-juanto** [comment]
The leader board automatically links the filename to the github profile page under the included name, and this breaks it.

@atesgoral ?

**Comment by atesgoral** [comment]
From the build failure, it's evident that the file path doesn't match the convention nn-Level-Name.sizePar.speedPar/size.speed.type-author.asm:

https://travis-ci.org/atesgoral/hrm-solutions/builds/97399765#L457

It should have been: `24.104.xor-jthermit.asm`

Also, shouldn't it be "xor" and not "x0r", if you mean exclusive or?

**Comment by nanashi-juanto** [comment]
See #209. There seems to be two users attributed as the solution's authors.

**Comment by atesgoral** [comment]
Ah, I see. Only the GitHub username of a single contributor needs to be in the filename because we auto-link to that contributor's GitHub profile. If there are other contributors that need to be credited, it's best done through comments in the program.

**Pull request closed without merging**
