### PR TITLE
Add columns for constrained solutions

### PR DESCRIPTION
**Pull request by jdashton**
Surface solutions that are the smallest or fastest within the constraint of achieving the other challenge for the level, e.g. "What's the smallest program that still meets the performance target?

### CODE REVIEW

**Comment by jdashton** [comment]
This is a feature that may have existed in the past and been removed, and if so, I apologize. However, I am interested in seeing this information on the leaderboard for two reasons:
1. It provides some balance against the willingness to forsake one goal in pursuit of the other. For example, the pursuit of speed while ignoring program size can lead to comparatively enormous programs.
2. It draws attention to some additional solutions in which a balance of goals was pursued, potentially putting some additional skilled programmers on the board.

**Comment by atesgoral** [comment]
Nice addition! I'll test locally and merge at the first chance.

**Comment by jdashton** [comment]
If there was one thing I wanted to add beyond the commits above, it would be some kind of indicator or badge to make it obvious when a given solution either A) satisfies both challenges or B) is the winning solution in both column C (size) & E (size within speed challenge) or both column D (speed) & F (speed within size challenge). But I haven't yet thought of a clear but unobtrusive way of presenting this information.

**Comment by atesgoral** [comment]
@jdashton I think it's time to move away from a simple `<table>` and cram all this information in a smarter layout.

**Pull request merged**
