### PR TITLE
Create 11.80-halchihal.asm

### PR DESCRIPTION
**Pull request by halchihal**
Is this OK ?

### CODE REVIEW

**Comment by viamodulo** [comment]
Yes but it's the same as https://github.com/atesgoral/hrm-solutions/blob/main/solutions/19-Countdown-10.82/11.80.obsolete-AaronKnowles.asm

**Comment by halchihal** [comment]
Oh, I see.

**Comment by halchihal** [comment]
The solution is Fastest That Meets Size Challenge of STAGE19

**Comment by viamodulo** [comment]
Yes indeed, that's why i created #360

**Pull request closed without merging**
